import ripadmin from "../../public/assets/videos/ripadmin.webm";
import ripbene from "../../public/assets/videos/ripbene.webm";
import pap from "../../public/assets/videos/pap.webm";
import tradu from "../../public/assets/videos/tradu.webm";
import movil from "../../public/assets/videos/movil.webm";
import planner from "../../public/assets/videos/planner.webm";
import difu from "../../public/assets/videos/difu.webm";
import toon from "../../public/assets/videos/toon.webm";

const webProjects = [
  {
    name: "movil",
    video: movil,
    technologies: [
      "git",
      "react",
      "html",
      "css",
      "js",
      "tailwind",
      "node",
      "mongo",
    ],
    images: [
      "movil1.png",
      "movil8.png",
      "movil2.png",
      "movil7.png",
      "movil3.png",
      "movil4.png",
      "movil5.png",
      "movil6.png",
    ],
  },
  {
    name: "pap",
    video: pap,
    technologies: [
      "git",
      "docker",
      "react",
      "html",
      "css",
      "js",
      "chakra",
      "node",
      "sql",
      "sequelize",
    ],
    images: [
      "pap1.png",
      "pap2.png",
      "pap3.png",
      "pap4.png",
      "pap5.png",
      "pap6.png",
      "pap7.png",
      "pap8.png",
      "pap9.png",
    ],
  },
  {
    name: "traducciones",
    video: tradu,
    technologies: [
      "git",
      "docker",
      "react",
      "html",
      "css",
      "js",
      "node",
      "sql",
      "sequelize",
    ],
    integrations: ["keycloak"],
    images: [
      "traducciones1.png",
      "traducciones2.png",
      "traducciones3.png",
      "traducciones4.png",
      "traducciones5.png",
    ],
  },
  {
    name: "difusiones",
    video: difu,
    technologies: [
      "git",
      "docker",
      "react",
      "html",
      "css",
      "js",
      "node",
      "sql",
      "sequelize",
    ],
    integrations: ["keycloak"],
    images: [
      "difu1.png",
      "difu2.png",
      "difu3.png",
      "difu4.png",
      "difu5.png",
      "difu6.png",
    ],
  },
  {
    name: "ripadmin",
    video: ripadmin,
    technologies: [
      "git",
      "react",
      "html",
      "css",
      "js",
      "chakra",
      "node",
      "mongo",
    ],
    images: [
      "ripadmin1.png",
      "ripadmin2.png",
      "ripadmin3.png",
      "ripadmin4.png",
      "ripadmin6.png",
      "ripadmin5.png",
    ],
  },
  {
    name: "ripbene",
    video: ripbene,
    url: "https://beneficiarios.ripalive.live/",
    technologies: [
      "git",
      "react",
      "html",
      "css",
      "js",
      "chakra",
      "node",
      "mongo",
    ],
    images: [
      "ripbene1.png",
      "ripbene2.png",
      "ripbene3.png",
      "ripbene4.png",
      "ripbene5.png",
    ],
  },
  {
    name: "planner",
    video: planner,
    technologies: [
      "git",
      "docker",
      "react",
      "html",
      "css",
      "js",
      "tailwind",
      "node",
      "sql",
      "sequelize",
    ],
    integrations: ["google"],
    images: [
      "planner1.png",
      "planner2.png",
      "planner3.png",
      "planner4.png",
      "planner5.png",
      "planner6.png",
      "planner7.png",
      "planner8.png",
    ],
  },
  {
    name: "toon",
    video: toon,
    technologies: [
      "git",
      "docker",
      "next",
      "react",
      "html",
      "css",
      "ts",
      "tailwind",
      "node",
      "sql",
      "prisma",
    ],
  },
];

export default webProjects;
